name: 'Terraform Apply'

on:
  release:
    types: [created]

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: development

    defaults:
      run:
        shell: bash

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: get release
      id: get_release
      uses: bruceadams/get-release@v1.2.2
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    
    - name: setup
      uses: hashicorp/setup-terraform@v1

    - name: init
      run: terraform init

    - name: workspace
      run: terraform workspace select ${{ steps.get_release.outputs.tag_name }} || terraform workspace new ${{ steps.get_release.outputs.tag_name }}

    - name: validate
      run: terraform validate

    - name: plan
      run: terraform plan -var environment=${{ steps.get_release.outputs.tag_name }}

    - name: apply
      run: terraform apply -auto-approve -var environment=${{ steps.get_release.outputs.tag_name }}
