name: 'Terraform Destroy'

on: 
  delete:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: development

    defaults:
      run:
        shell: bash

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Get branch names
      id: branch
      uses: tj-actions/branch-names@v4.3

    - name: credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    
    - name: setup
      uses: hashicorp/setup-terraform@v1

    - name: init
      run: terraform init

    - name: select workspace
      run: terraform workspace select ${{ steps.branch.outputs.current_branch }}

    - name: destroy
      run: terraform apply -auto-approve -var environment=${{ steps.branch.outputs.current_branch }}
      
    - name: remove workspace
      run: terraform workspace select default && terraform workspace delete ${{ steps.branch.outputs.current_branch }}
