name: 'Terraform Destroy'

on:
  delete:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: development

    defaults:
      run:
        shell: bash

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    
    - name: setup
      uses: hashicorp/setup-terraform@v1

    - name: init
      run: terraform init

    - name: workspace
      run: terraform workspace select $(echo "${GITHUB_REF}"  | cut -d/ -f 3) || terraform workspace new $(echo "${GITHUB_REF}"  | cut -d/ -f 3)

    - name: apply
      run: terraform destroy -auto-approve -var environment=$(echo "${GITHUB_REF}"  | cut -d/ -f 3)
